### ISSUE TITLE
How to disable encryption warning? (config text.greetings.before.encryption)

### ISSUE THREAD

**Issue by brknkfr** [etkecc/honoroit#1]
With https://github.com/etkecc/honoroit/commit/27e9971e5255f9264100c139cb519f4cdf6c2dc3 introduced a warning for encrypted rooms. Now our main honoroit (`HONOROIT_ROOMID`) gets spammed with 

````
Warning! This is an encrypted room, there is a high chance that we won't be able to read your messages. Please, consider using a non-encrypted room. If there is no other greetings message, that means that we can't read your messages.
````
when writing in threads. Is there a way to disable this?

**Comment by aine-etke** [comment]
Thank you for bringing it to our attention!
It should be fixed in [the latest release](https://github.com/etkecc/honoroit/releases)

**Comment by brknkfr** [comment]
Wow, that was fast ... Thank you!
